fs-snapshot: Exclude mount points recursively
rpm-software-management/yum-utils pull request #22
Opened 2017-06-24 21:03 UTC by nicksmith53

If `/home` is listed as excluded, exclude `/home/alice` and `/home/bob`

2017-06-25 03:00 UTC, james-antill commented
The problem is that there's no way to unexclude. So if a user wants to exclude / but expects the mountpoint for /usr to be snapshotted ... it's not possible.

2017-06-26 17:42 UTC, nicksmith53 commented
Ah good point. OK what about adding another option in the config file for `exclude_recursive`

2017-06-26 20:59 UTC, james-antill commented
Maybe better to have something like: exclude_glob = /home/*

If you'd prefer to just match prefixes then name it exclude_prefix (makes it more obvious that it's not walking the FS or something).

2017-11-08 13:50 UTC, dmnks requested changes
Please see my note inline.

2017-11-08 13:50 UTC, dmnks commented on docs/yum-fs-snapshot.conf.5
> +do not want to have snapshotted by this plugin. (e.g. "/mnt")
I would maybe add here an example of what having "/mnt" there would actually do (ie. basically the example in your commit message).

2017-12-14 17:25 UTC, nicksmith53 commented
Changed and rebased

2017-12-15 16:00 UTC, dmnks commented
LGTM

2020-02-12 14:41 UTC, dmnks commented
Thank you for the PR. However, please note that this project has been deprecated and is no longer maintained upstream. Please consider migrating to [DNF](https://github.com/rpm-software-management/dnf) which is the successor of YUM. That said, I’ll close this PR now.

2020-02-12 14:41 UTC, closed without merging